In [1]:
import numpy as np

# 전치(transpose)

In [40]:
array1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print('array : \n',array1,'\n')
transposed1 = np.transpose(array1)
print('transposed : \n', transposed1)

array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

transposed : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [41]:
array2 = np.array([[2],[4],[6]])
transposed2 = np.transpose(array2)
print('array1 * array2 = B: \n',np.dot(array1, array2), '\n')

print('(array1 * array2)T : \n', np.transpose(np.dot(array1, array2)),'\n')

print('(array2)T * (array1)T : \n', np.dot(transposed2,transposed1), '\n')

array1 * array2 = B: 
 [[ 28]
 [ 64]
 [100]] 

(array1 * array2)T : 
 [[ 28  64 100]] 

(array2)T * (array1)T : 
 [[ 28  64 100]] 



In [42]:
array3 = np.array([[2,3],[4,5],[6,7]])
transposed3 = np.transpose(array3)
print('array1 * array3 : \n',np.dot(array1, array3), '\n')

print('(array1 * array3)T : \n', np.transpose(np.dot(array1, array3)),'\n')

print('(array3)T * (array1)T : \n', np.dot(transposed3,transposed1), '\n')

array1 * array3 : 
 [[ 28  34]
 [ 64  79]
 [100 124]] 

(array1 * array3)T : 
 [[ 28  64 100]
 [ 34  79 124]] 

(array3)T * (array1)T : 
 [[ 28  64 100]
 [ 34  79 124]] 



# 내적(inner product)

In [45]:
A = np.array([[1],
              [2],
              [3]])

B = np.array([[4],
              [5],
              [6]])

inner_product = np.dot(np.transpose(A), B)

print('내적(inner product) =', inner_product)

내적(inner product) = [[32]]
